Adding a "Debugging" section to FAQ describing conda envs
showyourwork/showyourwork pull request #309
Opened 2023-02-21 20:45 UTC by rwegener2

This PR closes [SYW #299](https://github.com/showyourwork/showyourwork/issues/299) by adding a new section called "Debugging in showyourwork!’s conda environment". It describes how to find and activate the conda environment that snakemake creates.

While working on docs at the hackathon today some issues with the docs build environment came up (1. needing to explicitly install `datrie` via conda and 2. fixing the `import hacks` error). For the sake of small PRs and avoiding merge conflicts with someone else working on docs I did not include those group fixes in this PR.

Happy to hear any feedback!

2023-02-21 21:16 UTC, adrn requested changes
Looks great! A few minor edits suggested below.

2023-02-21 21:16 UTC, adrn commented on docs/faqs.rst
> +computer using ``conda env list``. The output will look something like this:
```suggestion
computer using ``conda env list``. On a Unix machine, the output will look something like this:
```

2023-02-21 21:16 UTC, adrn commented on docs/faqs.rst
> +Sometimes when debugging it can be helpful to bipass the ``showyourwork build`` command and
```suggestion
Sometimes when debugging it can be helpful to bypass the ``showyourwork build`` command and
```

2023-02-21 21:16 UTC, adrn commented on docs/faqs.rst
> +           /Users/rwegener/my-article/.snakemake/conda/28e8667c7a3a18371030aff088ceb5c5_
```suggestion
  base     /path/to/miniconda3
           /path/to/my-article/.snakemake/conda/28e8667c7a3a18371030aff088ceb5c5_
           
where "`/path/to/`" is often your home directory or wherever you installed Anaconda and cloned your article's repository.
```

2023-02-21 21:16 UTC, adrn commented on docs/faqs.rst
> +``/Users/rwegener/my-article/.snakemake/conda/28e8667c7a3a18371030aff088ceb5c5_``.
```suggestion
``/path/to/my-article/.snakemake/conda/28e8667c7a3a18371030aff088ceb5c5_``.
```

2023-02-21 21:16 UTC, adrn commented on docs/faqs.rst
> +To activate the environment, copy and paste that full path and run ``conda activate MY_ENV_PATH``.
```suggestion
To activate the environment, copy and paste that full path and run ``conda activate <full path>``.
```

2023-02-21 21:16 UTC, adrn commented on docs/faqs.rst
> +  conda activate /Users/rwegener/my-article/.snakemake/conda/28e8667c7a3a18371030aff088ceb5c5_
```suggestion
  conda activate /path/to/my-article/.snakemake/conda/28e8667c7a3a18371030aff088ceb5c5_
```

2023-02-21 21:16 UTC, adrn commented on docs/faqs.rst
> +From this point anything you run using the ``python`` command should use the same conda
```suggestion
From this point, anything you run using the ``python`` command should use the same conda
```

2023-02-21 21:16 UTC, adrn commented on docs/faqs.rst
> +--------------------
```suggestion
Debugging in |showyourwork|'s conda environment
-----------------------------------------------
```

2023-02-22 12:15 UTC, arm61 commented
Sometimes, in my experience, there is > 1 environment in `my-article/conda/` (I dunno why this), but maybe some comment on using the newest one (this is what I usually do)?

2023-02-22 13:03 UTC, dfm commented
Thanks @rwegener2! I think adding a note about @arm61's point is a good idea, but otherwise let's merge! 🚀

2023-02-22 13:04 UTC, dfm commented
I was also thinking that it might be worth adding a `showyourwork activate` command or something to streamline this process. Perhaps we should open a separate issue?

2023-02-22 18:16 UTC, rwegener2 commented
Thanks for the comments, everyone! All the suggestions have been added, so I think this is set to merge.

2023-02-22 18:28 UTC, adrn approved these changes

2023-02-22 20:36 UTC, merged

2023-02-22 20:36 UTC, dfm commented
Thanks @rwegener2!!